commands:
    - command:
      input:
          - What time is it?
          - Tell me the time.
          - Time.
      entity: time
      action: getTime
    - command:
      input:
          - What date is it?
          - Tell me the date.
          - Date.
      entity: time
      action: getDate
    - command:
      input:
          - What year is it?
          - Tell me which year is it.
          - Year.
      entity: time
      action: getYear
    - command:
      input:
          - What the weather?
          - What the weather like?
      entity: weather
      action: getWeather
